# OVRO-LWA HEALPix nested-tile detect (Option 2)

Experiment: coadd hourly FITS onto a **HEALPix** map (`nside_map=2048`), write MAP+WEIGHT FITS,
export a **HiPS** directory (same stem, `.hips` suffix), project **nested** tiles
(`nside_tile=4`, TAN, overlap 0.2) via `reproject_from_healpix`, then
`run_pybdsf_on_hdu` on each tile — once per band in `COLOR_BANDS`.

Tile catalogs are collapsed with `merge_tile_metacatalog` into **LST-merged-shaped**
Parquets (`metacatalog_lst_{band}.parquet`), then fused with the same
**band merge** path as `ovro_lwa_metacatalog.ipynb` (`build_global_metacatalog`).

This is a sibling to `ovro_lwa_mosaic_detect.ipynb` (planar SIN coadd). It does **not** replace
the per-hour → LST-merge catalog pipeline.

**Notes**
- Do **not** call `blank_below_elevation` on tile HDUs (CRVAL is tile center, not zenith).
- Elevation blanking uses an **elliptical** horizon cut (`min_elevation_ns` / `min_elevation_ew`) on native hourly WCS.
- Overlap duplicates are merged (brightest flux); `n_lst_contributions=1` (single coadd).
- Requires `lwa-catalog[analyze,detect]` and a current editable `lwa-healpix`.

In [1]:
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from astropy.io import fits

from lwa_catalog.constants import ASSOC_BANDS, BAND_FIELDS, BAND_FLUX_FIELDS
from lwa_catalog.create.discover import discover_fits_files, discovered_slots
from lwa_catalog.create.healpix_detect import (
    detect_sources_on_healpix_tiles,
    median_beam_from_paths,
    restfreq_hz_from_header,
)
from lwa_catalog.create.merge import build_global_metacatalog, merge_tile_metacatalog
from lwa_catalog.io import (
    lst_merged_cache_complete,
    read_all_lst_merged,
    write_lst_merged,
    write_metacatalog,
    write_table,
)
from lwa_catalog.paths import CatalogLayout
from lwa_healpix import (
    coadd_fits,
    healpix_to_hips,
    parallactic_delta_q_edge_summary,
    read_healpix_fits,
    write_healpix_fits,
)

# --- paths (edit for your machine) ---
FITS_ROOT = Path("/lustre/pipeline/exopipe/phase3/Coadd/Run_20260909_000000/")
# Glob(s) relative to FITS_ROOT (rglob). Band comes from the path/filename
# (see Filename parsing / COLOR_BANDS below).
FITS_GLOB = "??h/[RGBF]*/*_I_deep_Taper_Robust-0.75_shflux_pbcorr*fits"
OUTPUT_DIR = Path("/fast/claw/healpix_tile_detect2")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
layout = CatalogLayout(OUTPUT_DIR)

REUSE_HEALPIX_FITS = True
REUSE_HIPS = True
# Skip tile detect + tile→LST merge when metacatalog_lst_*.parquet exist for COLOR_BANDS
REUSE_CACHED_CATALOGS = True

NSIDE_MAP = 2048
NSIDE_TILE = 4
OVERLAP = 0.2
MIN_ELEVATION_NS_DEG = 15.0  # N/S horizon cut (looser)
MIN_ELEVATION_EW_DEG = 40.0  # E/W horizon cut (stricter)
COORD_FRAME = "icrs"  # reproject: icrs/c or galactic/g
NESTED = True

BDSF_KW = dict(
    thresh="hard",
    thresh_isl=2.5,
    thresh_pix=3.5,
    rms_map=True,
    savefits_rmsim=False,
    outdir=str(OUTPUT_DIR),
    kappa_clip=3.0,
    rms_box=(128, 32),
    adaptive_rms_box=True,
    rms_box_bright=(32, 8),
    adaptive_thresh=50.0,
    atrous_do=False,
    psf_vary_do=False,
    quiet=True,
    ncores=1,
)


def healpix_fits_path(band: str) -> Path:
    return OUTPUT_DIR / f"healpix_{band}_nside{NSIDE_MAP}.fits"


def healpix_hips_path(band: str) -> Path:
    return healpix_fits_path(band).with_suffix(".hips")


def tile_catalog_path(band: str) -> Path:
    return OUTPUT_DIR / f"sources_healpix_tiles_{band}.parquet"

## Filename parsing

Discover FITS under `FITS_ROOT` and parse LST hour / color band from filenames
(`lwa_catalog.create.discover`). Band names are defined as notebook constants below.

In [2]:
# Explicit catalog constants (notebook-local; passed into library APIs below)
COLOR_BANDS = ("Full", "Blue", "Green", "Red")

In [3]:
_fits_patterns = (FITS_GLOB,) if isinstance(FITS_GLOB, str) else tuple(FITS_GLOB)
fits_files = discover_fits_files(FITS_ROOT, patterns=_fits_patterns)
slots = discovered_slots(fits_files)

paths_by_band: dict[str, list[Path]] = {}
for band in COLOR_BANDS:
    by_lst: dict[str, object] = {}
    for m in fits_files:
        if m.band != band:
            continue
        by_lst.setdefault(m.lst_hour, m)
    paths_by_band[band] = [by_lst[h].path for h in sorted(by_lst)]
    print(
        f"{band}: {len(paths_by_band[band])} LST hours from "
        f"{sum(1 for m in fits_files if m.band == band)} discovered files"
    )

print(f"Found {len(fits_files)} FITS under {FITS_ROOT} matching {list(_fits_patterns)}")
print("slots sample:", list(slots)[:5], "...")

Full: 24 LST hours from 24 discovered files
Blue: 24 LST hours from 24 discovered files
Green: 24 LST hours from 24 discovered files
Red: 24 LST hours from 24 discovered files
Found 96 FITS under /lustre/pipeline/exopipe/phase3/Coadd/Run_20260909_000000 matching ['??h/[RGBF]*/*_I_deep_Taper_Robust-0.75_shflux_pbcorr*fits']
slots sample: [('00h', 'Blue'), ('00h', 'Full'), ('00h', 'Green'), ('00h', 'Red'), ('01h', 'Blue')] ...

## Parallactic-angle edge check

At the elliptical elevation-mask edge, compute 1-hour parallactic-angle change
(`Δq`) toward 8 cardinal directions (N, NE, …, NW). Large `|Δq|` means an
elongated PSF would rotate substantially between adjacent LST hours that still
pass the mask — a projection/stacking-error diagnostic complementary to the
stricter E/W cut.

In [4]:
dq_rows = parallactic_delta_q_edge_summary(
    min_elevation_ns=MIN_ELEVATION_NS_DEG,
    min_elevation_ew=MIN_ELEVATION_EW_DEG,
)
dq_table = pd.DataFrame(dq_rows)
display(
    dq_table[
        [
            "direction",
            "az_deg",
            "elev_edge_deg",
            "dec_deg",
            "dq_range_deg",
            "abs_dq_min_deg",
            "abs_dq_median_deg",
            "abs_dq_max_deg",
        ]
    ].round(3)
)
print(
    f"Max 1-hour |Δq| among edges: "
    f"{dq_table['abs_dq_max_deg'].max():.2f} deg "
    f"({dq_table.loc[dq_table['abs_dq_max_deg'].idxmax(), 'direction']})"
)

,direction,az_deg,elev_edge_deg,dec_deg,dq_range_deg,abs_dq_min_deg,abs_dq_median_deg,abs_dq_max_deg
0,N,0.0,15.000,67.760,10.914,12.200,12.888,23.114
1,NE,45.0,31.165,52.642,33.057,9.844,11.390,42.901
2,E,90.0,40.000,22.891,56.958,0.057,7.181,43.297
3,SE,135.0,31.165,-9.702,41.483,0.234,7.274,25.270
4,S,180.0,15.000,-37.760,86.772,5.320,7.662,92.092
5,SW,225.0,31.165,-9.702,41.483,0.234,7.274,25.270
6,W,270.0,40.000,22.891,56.958,0.057,7.181,43.297
7,NW,315.0,31.165,52.642,33.057,9.844,11.390,42.901

Max 1-hour |Δq| among edges: 92.09 deg (S)

In [5]:
# Coadd (or reuse) HEALPix FITS per band, then write HiPS (stem + .hips)
band_maps: dict[str, dict] = {}

for band in COLOR_BANDS:
    paths = paths_by_band.get(band, [])
    if not paths:
        print(f"{band}: skip (no FITS)")
        continue

    healpix_fits = healpix_fits_path(band)
    hips_dir = healpix_hips_path(band)

    if REUSE_HEALPIX_FITS and healpix_fits.is_file():
        healpix_map, weight, meta = read_healpix_fits(healpix_fits)
        print(
            f"Reused {healpix_fits}: nside={meta['nside']} "
            f"nested={meta['nested']} frame={meta['coord_frame']}"
        )
    else:
        healpix_map, weight = coadd_fits(
            paths,
            nside=NSIDE_MAP,
            nested=NESTED,
            coord_frame=COORD_FRAME,
            min_elevation_ns=MIN_ELEVATION_NS_DEG,
            min_elevation_ew=MIN_ELEVATION_EW_DEG,
        )
        write_healpix_fits(
            healpix_fits,
            healpix_map,
            weight,
            nside=NSIDE_MAP,
            nested=NESTED,
            coord_frame=COORD_FRAME,
            overwrite=True,
        )
        print(
            f"Wrote {healpix_fits}  "
            f"weight>0={(np.asarray(weight) > 0).sum()} / {weight.size}"
        )

    if REUSE_HIPS and hips_dir.is_dir() and any(hips_dir.iterdir()):
        print(f"Reused {hips_dir}")
    else:
        if hips_dir.exists():
            shutil.rmtree(hips_dir)
        healpix_to_hips(
            healpix_map,
            coord_frame=COORD_FRAME,
            output_directory=hips_dir,
            nested=NESTED,
        )
        print(f"Wrote {hips_dir}")

    bmaj, bmin, bpa = median_beam_from_paths(paths)
    restfreq = restfreq_hz_from_header(fits.getheader(paths[0]))
    print(
        f"{band}: median beam BMAJ={bmaj:.5f} BMIN={bmin:.5f} BPA={bpa:.3f} deg  "
        f"RESTFREQ={restfreq:.3e} Hz"
    )
    band_maps[band] = {
        "healpix_map": healpix_map,
        "weight": weight,
        "bmaj": bmaj,
        "bmin": bmin,
        "bpa": bpa,
        "restfreq": restfreq,
    }

WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]

Wrote /fast/claw/healpix_tile_detect2/healpix_Full_nside2048.fits  weight>0=40456680 / 50331648
Wrote /fast/claw/healpix_tile_detect2/healpix_Full_nside2048.hips
Full: median beam BMAJ=0.14599 BMIN=0.13168 BPA=42.706 deg  RESTFREQ=5.245e+07 Hz

WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]

Wrote /fast/claw/healpix_tile_detect2/healpix_Blue_nside2048.fits  weight>0=40456680 / 50331648
Wrote /fast/claw/healpix_tile_detect2/healpix_Blue_nside2048.hips
Blue: median beam BMAJ=0.10472 BMIN=0.09415 BPA=43.523 deg  RESTFREQ=7.541e+07 Hz

WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]

Wrote /fast/claw/healpix_tile_detect2/healpix_Green_nside2048.fits  weight>0=40450176 / 50331648
Wrote /fast/claw/healpix_tile_detect2/healpix_Green_nside2048.hips
Green: median beam BMAJ=0.14516 BMIN=0.13287 BPA=42.710 deg  RESTFREQ=5.245e+07 Hz

WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]

Wrote /fast/claw/healpix_tile_detect2/healpix_Red_nside2048.fits  weight>0=40383776 / 50331648
Wrote /fast/claw/healpix_tile_detect2/healpix_Red_nside2048.hips
Red: median beam BMAJ=0.21995 BMIN=0.20253 BPA=39.738 deg  RESTFREQ=2.948e+07 Hz

In [6]:
tile_catalogs: dict[str, pd.DataFrame] = {}
lst_merged: dict[str, pd.DataFrame] = {}

if REUSE_CACHED_CATALOGS and lst_merged_cache_complete(layout, COLOR_BANDS):
    lst_merged = read_all_lst_merged(layout, COLOR_BANDS)
    for band in COLOR_BANDS:
        print(
            f"Tile→LST ({band}): loaded {len(lst_merged[band])} sources from "
            f"{layout.lst_merged(band).name}"
        )
else:
    for band, payload in band_maps.items():
        out = tile_catalog_path(band)
        catalog = detect_sources_on_healpix_tiles(
            payload["healpix_map"],
            payload["weight"],
            nside_map=NSIDE_MAP,
            nside_tile=NSIDE_TILE,
            overlap=OVERLAP,
            coord_frame=COORD_FRAME,
            nested=NESTED,
            bmaj=payload["bmaj"],
            bmin=payload["bmin"],
            bpa=payload["bpa"],
            restfreq_hz=payload["restfreq"],
            band=band,
            bdsf_kw=BDSF_KW,
            skip_empty=True,
        )
        write_table(catalog, out)
        tile_catalogs[band] = catalog
        n_tiles = catalog["tile_ipix"].nunique() if len(catalog) else 0
        print(f"Wrote {out}: {len(catalog)} raw tile rows, {n_tiles} tiles with sources")

        merged = merge_tile_metacatalog(catalog, band=band)
        lst_merged[band] = merged
        lst_path = write_lst_merged(merged, layout, band)
        print(
            f"Tile→LST ({band}): {len(catalog)} tile rows → {len(merged)} sources -> {lst_path.name}"
        )

    # Empty bands still need keys for build_global_metacatalog
    for band in COLOR_BANDS:
        if band not in lst_merged:
            lst_merged[band] = pd.DataFrame()

# preview
for band, catalog in lst_merged.items():
    if len(catalog):
        print(f"\n=== {band} LST-merged-shaped head ===")
        display(catalog.head())
        break

stty: 'standard input': Inappropriate ioctl for device
/opt/devel/claw/envs/py312/lib/python3.12/site-packages/bdsf/gausfit.py:806: RuntimeWarning: overflow encountered in cast
  if A < opts.flag_minsnr*thr:
WARNING: Total flux density in model is 2.24 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9wrubiat.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpk9r7pdv6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpy5bb38kq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_g2w1zf1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpro4wmy46.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpo71_jf23.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_ue474pe.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplipcn_pw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpehv1pozg.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpj7bhk82j.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpicpgl4pv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.25 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7jn06pfx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpe0a4xx9i.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_4hkdrjb.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp49dcck8r.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdbvr4er9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfzj3aa_u.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpo6q3kpox.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.26 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1592mefy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjx7zqaxn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1awbpih_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3pc6p0rr.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjrhr892c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi_zctaaq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1negokzl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfgo4ajp3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm30tsuzx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device
/opt/devel/claw/envs/py312/lib/python3.12/site-packages/bdsf/functions.py:624: RuntimeWarning: Number of calls to function has reached maxfev = 1400.
  p, success = leastsq(errorfunction, p_ini)

--> Wrote FITS file '/tmp/tmp5poa01vx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7drxt2q5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9fyf_f35.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.18 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp336mufso.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3deay9zd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppmv9dkdm.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqk80rcl6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp17tjdxm0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9xtlie7x.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.29 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpj5e901xp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.25 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpp9251qoe.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgdx69xry.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmph8dc4wze.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2ihzh4nn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpru3y8dsu.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp08p9uc5e.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcw3mhpwk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqahz86y2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpc4aov6y8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn8p8897o.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbciliepq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxwt7shnz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfg9tlg_v.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpilv8dq87.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphvltjeh6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.31 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxe6_g_78.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpet7cx448.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.42 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjqy8mz77.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.41 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8tqyhv77.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqdeb5ot8.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplv56o6x_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpp6g5cek9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpe5kob6t6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmph5xmta_c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptvfcwkby.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphk4wo9ta.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcafa9vt9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpheggpphy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpekuvsy8l.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_fg49m1q.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwe9izlfy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3hwrs9ou.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8onp0c8r.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.43 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbag1jplb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp84rve14f.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptas_4eqf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.38 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpitjgdkd2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprd1u4vmp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6ncws13_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.31 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdcud6y07.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcfxfrn_z.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxnu65eeb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpy09rbnlh.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6f9xlnn4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpz81q4z43.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.36 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptiwkjtx0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.29 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpql9x4ym1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnkvrelc9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5ztuwucs.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxf_dyxmt.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmpqvkxqb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprviabyfw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp__kbnqys.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp16ia81zv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3xiy0pkm.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjzh_fu27.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpf2we2zsc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9bt_t3bk.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzvx2_aay.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpo81z_2j7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpty_zrs19.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6ahuw0ag.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptdrqhrl3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpq744m50i.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpf9orsz36.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp54ik65yy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp39u6xydg.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpznrm7zrd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp90cwln5l.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.42 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqhfm8wiw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.26 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm28vzlb3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp59pbez_h.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpq5o65qyq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzv6phcw8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpycejkr1j.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpa0qmeso5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpstpc5z1t.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.80 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpasxgjg5g.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.32 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp23vvh1yz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.51 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdyg3bux8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7i5ayweo.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpczr0vtd1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsnxpjxtp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.86 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjq1s550j.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpecy2sb04.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprft81gq3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp85hr6210.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpp6o75jl8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl5mpfsoo.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_jjlmgf7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.00 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyfrjar73.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpoltd0smq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9j23_ei8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0d4lu6c7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpuzid6wvz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4nl_p8hp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn8yj4_gz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4eu3pvhe.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6w3dbcr8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqet019zv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzb7vyrhg.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpg8nnawtq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 0.40 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvkb5mjdf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwwwvfcp_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 4.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfakle8t5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgubsy8qz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpglwg_pg_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjllym7n8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbzfk4fho.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpj16psk1c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzp55rfnz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfy2a7is7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpid7yi35w.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprubycmnx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.47 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcpft4te4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkojlelik.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2a8224qt.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_ohfrwhm.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2efpco_1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpud5b9g1l.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_xo5tbtj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpefmpvxyf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.91 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp24fdsub6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.53 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkebmieqq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyl23ko97.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpust1btjt.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpaawrzj53.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdaeosg5k.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjq0608p6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.71 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7t017o0q.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplq06pqu8.gaul.fits'
Wrote /fast/claw/healpix_tile_detect2/sources_healpix_tiles_Full.parquet: 96835 raw tile rows, 168 tiles with sources
Tile→LST (Full): 96835 tile rows → 63059 sources -> metacatalog_lst_Full.parquet

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.00 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl6gfoayc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpd_ambdwj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvevk5hph.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp28ciw362.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7kml33ah.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnn5_jpws.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpil38tz2o.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp88q9ficv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpouheql35.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4zos5wx7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpu52gc4bh.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpku36dpq1.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfbfzhhg6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfbitddcw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpww16zo_n.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwydey6rf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqswi4b8d.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4w8k678p.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpowvvj3fu.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpycd0wnge.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp29pktq8z.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5ypqix96.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpapv219v_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcm_22ct0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzwi1hvuz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp30k6az7u.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp415beimp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjvp7dt8h.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgo9uq4_6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphkri_evk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcp0sutzt.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5c1lnh6v.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpig9b4tpb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpugq6b5sj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpeg17sabb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4n005601.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyk5n2n5n.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6_dqvxrs.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkflx_bd8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnu_abaai.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphab2th_c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpc1ndc_bn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp99ij1txg.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.00 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyzrul7_2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4y5qedao.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5m7bj5ms.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_y4zy4gr.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpj5hstmuc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpv0len96p.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl7jnkpek.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbjmm8x68.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpattzfm6z.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8jpsm529.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpeo5gif7d.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmparbr2p_g.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.39 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxxsty88q.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl_np9xyl.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpssixjfro.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphxvtpwo2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphzo7iaav.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjkif8xpv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpymu2gkpo.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6kwohxcd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwmkz6sui.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjl4ld294.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpaj030qlk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgcsuxabj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3ii2ae7c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpifoav6j7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0ybvh0r5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpu1uu4vqt.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsg7r5xfj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpssdczxyo.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp087jzu8o.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpk9_i3qlg.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwhsib5py.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplbxfz3up.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpd3qhvo08.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppn2abbig.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0opqj9_1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7tx2vmmz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbjmo94z3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.25 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1otmx7e2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4fh8v68c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzr1z67je.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0dwyo1mx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp88ywm0k8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmrojd3jj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsu826fpw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpuwf2xu_8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn4jefvit.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnkdo62hg.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7wvifuob.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpebh3vgz0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpin9yeoe1.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptablp6qi.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpx6_x3bks.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.18 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2sbn8afg.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp10ouj6gk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device
/opt/devel/claw/envs/py312/lib/python3.12/site-packages/bdsf/functions.py:624: RuntimeWarning: Number of calls to function has reached maxfev = 1400.
  p, success = leastsq(errorfunction, p_ini)

--> Wrote FITS file '/tmp/tmp6oexvv_m.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1eq6kwal.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpd5ot2tve.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbmuta0ax.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdzbqq2l5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpac92wa_g.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprleed_4e.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmph4nif_7_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpg75t6ghq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpygttug8w.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpky3td75s.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprwqhkhmz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4p7or7ej.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 0.43 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnhvx_lfs.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcqxe78bx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 9.56 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmps85q65hl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmrhwh5eq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.75 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdnp2x5r9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnyijp1ow.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpja7rge3n.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdq4m3vb7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.71 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpaukn5jm3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpw63vr_pk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpk5db35m3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzop9ax72.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl2k4txvn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.25 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp76l7f2a4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprrxuaukr.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvf3s2qvy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpc45ddd9v.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp49lxjfdd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_yen22a9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpt3an3n5w.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkgxmq585.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplofx69ed.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppu7lalef.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_onm6wwn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphy7fyuks.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyug1p7un.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwq768xxl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdpnsuom6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprsy4ncqr.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.58 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8qb7ep5n.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfsgjymj2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpy0gatuky.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwlxl_1ol.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9h0cxgiw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmf2rg795.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjacvoba6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpekjw6br1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmmsu0in1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpciwz9hj5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptw86nglw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7svbcy2l.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl0k7sbqc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.44 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1xjd_byj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbn_ka067.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbxb_4mb3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpc45z4pjj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcr2vx23q.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0dfiaz2y.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpskytrzhw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpc6trbedl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2pc4rykx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpt1td54nw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7vid2lt4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpstkrf3g2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.49 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpofsexb2d.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkbutw7kg.gaul.fits'
Wrote /fast/claw/healpix_tile_detect2/sources_healpix_tiles_Blue.parquet: 207094 raw tile rows, 168 tiles with sources
Tile→LST (Blue): 207094 tile rows → 135778 sources -> metacatalog_lst_Blue.parquet

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.33 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppnjq_yx0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi_t2d1pm.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpb2rp644i.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcllpbmrf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptj0apqiq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxn_gyw14.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.25 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcui9kkrk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5lntzyxf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.39 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3i5md7pp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_gud39sb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi4bbc0rs.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.34 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqtbux4bq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8y4siujh.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptyh1qkrj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmsxq85r5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpme9_3pa4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.38 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpoiga4c_r.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgn813p4m.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjg13i2im.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm2i0pqp4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm9kpyxpk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptrll10f_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp47hk1ovi.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpw91vf0dz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmph_8b46ki.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprshkn0nd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpq_ltu03p.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpivyccvhc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfyslg2lv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsdn_f9xb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppxnu75jx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.26 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdwo8o_px.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpd8e7dt7g.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxwyyxfvs.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgb_74_lt.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjri4afl5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.44 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1dxu55yv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.33 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_lc1zbi0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqfc7kn9_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptv99p56u.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpddb8ilrf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.51 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnndmnia4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1i3fqyt6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpr9teut89.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.33 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0tv_dwfs.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphoqvf4nk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpa_i8scly.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm1g8malp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.30 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp264l084_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.18 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp74cij35j.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6zit6my5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpus_vc3gd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvoretptf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9dlbbjye.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.54 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpixb043kl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.65 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm6fzlhm3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpat8w6kc0.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpck0xbk_t.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_fgmoqig.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptw2a5v0z.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphff2nue_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpniwn9kw7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfx1wxpfd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_mm38uye.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9fpa0g22.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi1ywxiza.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.00 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpy7sq66s1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpj1ni5wiw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppocg8p7f.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.31 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmps3zla6x9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.43 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpra7vr27q.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.26 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcyo6jhkk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpt49pol8v.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.48 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpubh_pfgj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.34 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpljysb2iq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.24 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2cstz3bv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpeixx0g2u.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.26 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpp4ag35wo.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6x5ydpf6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi9cnvpkq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpt7gkefk5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmph6taldif.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.52 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp29rnc7rr.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.29 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplh28h32e.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplxffjpia.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.46 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0jb9p499.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1igwpu7e.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyf1pdl3i.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.33 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpeycv27rl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl8_lge7k.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.30 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyimxqo77.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpaz6gbxva.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpo49v4k0z.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0swsmfdv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbf5ppfiy.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp53r2b57k.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5opvvofj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.32 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcvmiciy5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp09vehr2o.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.02 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7roqi2f2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.29 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9uyh10y5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpa0q2nc04.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwmr21hth.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpges3foc6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpp2_u0r3o.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpy_ly3sdi.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.46 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5hkq6p9g.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.33 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpheu0qna6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi_w2xsyp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpq8r1sa8u.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkxh51acb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpy5suhdx4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpb30iz0s6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.45 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1iyyytso.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 7.86 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5ke0sy1h.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.45 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpckpa6luz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.62 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsu0_xsa8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0dw_2ftw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgs0820bc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpawpox9mm.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.80 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjvipxi7o.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmph8lo81ps.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpon8c96ub.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8vv4yzv2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpb5vzhlmj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptj1epa16.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdaf3lnow.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn08fotjy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpujg0hbg6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp392xei44.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm7w28gos.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppy3q566c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpapdq58l3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4onphfwj.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp__symgns.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdpixsqso.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyducm_c_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpabsf45_s.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6n6a438y.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 0.38 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi9h3irwy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkgede53p.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.44 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcj5l9ykx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjwk9p3rz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpufksvj9_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpr4wjcv3c.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpe4nw_cvk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpre16twqn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyedm87rb.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpysahz603.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpce1h_few.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpopdgg9kt.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.61 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6u2nyowo.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpffqtth0j.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6x0v_bq3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.30 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl5nv6xm6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpq4g5ea5q.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpk9hvv1p1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphexibuhb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsbuelw2b.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.92 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8k_de9al.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.77 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp83pbzw5f.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpg4l1acd5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkb_w6new.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqgvxy7_z.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfjsyzvep.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpdl2i30q7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.85 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkfk7gdsv.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnwjydoum.gaul.fits'
Wrote /fast/claw/healpix_tile_detect2/sources_healpix_tiles_Green.parquet: 107859 raw tile rows, 168 tiles with sources
Tile→LST (Green): 107859 tile rows → 72372 sources -> metacatalog_lst_Green.parquet

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfvoydxce.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.53 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp74bugjdh.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.60 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqhl12f9a.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.53 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp20yo0tgs.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvxlim8pf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.52 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpu6c1ky57.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.39 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpemelks74.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpw_p6her1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.59 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpaw2dzlic.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.39 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpy0tfgsif.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.38 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjzq133e_.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.50 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpt4rh5aw6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpws1q4je0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.00 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9ax6xphv.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4mz0nfxq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1ifgyacy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.34 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcrifrvim.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.36 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2857pdua.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.61 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbxvgbgjn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.33 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp53oh_fm3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.43 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_g6mnwpv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.45 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqxjjmfwk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.43 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpinlju2b8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnwu73vyx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi6jj7ops.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.46 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptsdjtp_h.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm3vp8b4b.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpz_xfdyym.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.42 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1vn2ofeu.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1b9j6ta7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.43 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn8a2n0fw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.46 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpzakyjb19.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.24 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpg0q8374x.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmh8nudlf.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpainw8mn3.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.42 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmparg9nq41.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.60 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptizb8g8x.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.66 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp4iqu5pr6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.24 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8f9zo52f.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.56 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp7gi7krur.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.33 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxaor80hq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.50 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp76c0dxmd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.56 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5vpepepz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpi256lqnl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.59 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpd9spvg08.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_blyjl7w.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5utv1l3m.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpv7ihjnzb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkh9klxla.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpniz38vrv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.38 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpoft8nt_r.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0xfgpqof.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.91 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp291y393v.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpeoo92slj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.50 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3s00v07e.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.50 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm05ugc1_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpg7gij5x0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.09 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptgx6c3s9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.20 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcnlv9zxk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9ixgl5pn.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6b6e985k.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.04 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_cj_6h6z.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.47 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp73gv1zj1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.49 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpj_5zkgvn.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmptp1uqnd1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphakx2e6p.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9iocdtnb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp16a6lnl6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp58zvcr3s.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.52 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpbwokscri.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.72 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpagwlepyw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.50 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpyqveb83b.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmplsu1j2_m.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.51 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8urgc8d9.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.45 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpv96_bn6s.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmprdcjsrul.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.74 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp_sbo1ukj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.45 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvstbpze4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.32 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsnpgc3_h.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.42 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn86o2mjy.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.16 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpm0ov4u72.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpz64clfj_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.45 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp774fr2t1.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.53 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpul_5s1x6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpb3k248rh.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.67 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpqly7q5iw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.13 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpb_gk23g7.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.41 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpjeiee6wb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.52 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl6k0bnkx.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn5qna2pd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.60 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1rpaiamh.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp35ewvl6x.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.31 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp270_ada0.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpq2u_ip8k.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.29 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcmwt0vzv.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3punsncd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp52csw8xi.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.54 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpd3w19tx8.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp42jgfxtw.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.10 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpve9m0616.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.30 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp118gfsbe.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.23 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpphk1e8w2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpn8o9_gw_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.01 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpd_4a99gp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.18 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnn4z3y5a.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.22 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3m49ml32.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.85 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpk3_er_hc.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.60 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpf8ougaqq.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.15 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6kp7u2dy.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3c80e1vu.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.17 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1s_ofquv.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0fir6lkk.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp5lj9tnz4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 5.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpv7y_xla7.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmph4lnkmol.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 17.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpgr2grh0x.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 4.14 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpz5prkrqu.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.25 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphkfjzvsb.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpnm7arnz5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpit24z59r.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 4.84 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2ehuwd65.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpsycui6h6.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9l3ugo9n.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpxs3bhqrc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpwev_9pen.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmps8_82wfl.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.11 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3f2vxhdj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.19 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp6rdjutvh.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpu2p2op0w.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 0.32 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmphj3t9ux2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppt7khwur.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp3_germzu.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpf9_unyud.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpk8tlay4b.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkj37lmua.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.03 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp1nk1uvjh.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.18 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpowae75jb.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpalxk61ej.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpb719xn9e.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 0.27 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpj6u05pk4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl8wt0z13.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpcuugytyd.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvtnphyka.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpexpa655e.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpaabweurp.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpucwzmonq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmporr2yy76.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.28 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0t3k9624.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

No sources were found in the image. Output file not written.

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpatd0lktq.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfm0ski66.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.05 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkib5d_ed.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfu0d1cn2.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.37 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpl2w2z2kz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.99 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp0vw6ivsz.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.12 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp8koow4y0.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.21 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpr25oq4j4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpluoy177_.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpmj7jc2uj.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.59 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpkbkmzata.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.06 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpujefh_ed.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmppkwenjt4.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 0.08 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpe5adnfyc.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpvcf6tcxt.gaul.fits'

WARNING: Negative values found in rms map interpolated with spline_rank = 3
WARNING: Using spline_rank = 1 (bilinear interpolation) instead
stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp9u9rtdv5.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmps1p5um0o.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 3.35 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmpfyd3zzef.gaul.fits'

stty: 'standard input': Inappropriate ioctl for device
WARNING: Total flux density in model is 2.07 times sum of pixels in input image. Large residuals may remain.
stty: 'standard input': Inappropriate ioctl for device

--> Wrote FITS file '/tmp/tmp2014c85e.gaul.fits'
Wrote /fast/claw/healpix_tile_detect2/sources_healpix_tiles_Red.parquet: 40105 raw tile rows, 167 tiles with sources
Tile→LST (Red): 40105 tile rows → 27646 sources -> metacatalog_lst_Red.parquet

=== Full LST-merged-shaped head ===

,RA,DEC,Total_flux,E_Total_flux,Peak_flux,E_Peak_flux,Maj,Min,PA,DC_Maj,...,nside_tile,band,BMAJ,BMIN,BPA,n_lst_contributions,lst_hours,representative_lst,Peak_flux_std,cluster_jitter_rms_deg
0,252.783810,4.997168,547.664285,5.438492,261.840041,1.848951,0.232540,0.169107,39.015479,0.182772,...,4,Full,0.145989,0.131682,42.70555,1,,healpix,115.898930,0.115507
1,260.127056,-0.981342,368.881998,3.117241,244.783882,1.355441,0.175820,0.164556,171.611618,0.112826,...,4,Full,0.145989,0.131682,42.70555,1,,healpix,77.433809,0.106295
2,139.533542,-12.096558,656.826543,13.330707,199.517386,3.176712,0.322079,0.194165,165.413415,0.292237,...,4,Full,0.145989,0.131682,42.70555,1,,healpix,73.970763,0.035702
3,51.013614,-37.292113,1857.036291,11.221711,188.118573,1.035078,0.674694,0.271376,3.312137,0.660443,...,4,Full,0.145989,0.131682,42.70555,1,,healpix,68.708411,0.117262
4,50.477441,-37.572627,32.039350,0.859380,172.616181,0.324877,0.189605,0.018159,85.894449,0.000000,...,4,Full,0.145989,0.131682,42.70555,1,,healpix,111.605729,0.025681

## Metacatalog fusion

Tile detections are already collapsed to one row per sky position per band
(`merge_tile_metacatalog` → `metacatalog_lst_{band}.parquet`), equivalent input to
the usual LST-merged catalogs.

**Band merge** (Full→Blue→Green→Red): cross-match those catalogs and fuse into
one row per sky position (`build_global_metacatalog`). Primary `RA`/`DEC`/`Peak_flux`/
`Total_flux` come from the seed band (`origin_band`). Associated bands contribute
**per-band columns** from `BAND_FLUX_FIELDS` — e.g. `Peak_flux_Blue`,
`E_Peak_flux_Green`, `Peak_flux_std_Red`. Spectral indices use
`Total_flux_{band}` and `E_Total_flux_{band}`.

In [7]:
# LST-merge schema collapses tile overlap; band merge copies flux per band.
assert BAND_FLUX_FIELDS == (
    "Peak_flux",
    "Total_flux",
    "E_Peak_flux",
    "E_Total_flux",
    "Peak_flux_std",
)
for col in BAND_FLUX_FIELDS:
    assert col in BAND_FIELDS


def per_band_flux_columns(bands: tuple[str, ...] = COLOR_BANDS) -> list[str]:
    """Metacatalog column names for per-band flux preservation."""
    cols: list[str] = []
    for band in bands:
        for field in BAND_FLUX_FIELDS:
            cols.append(f"{field}_{band}")
    return cols

In [8]:
metacatalog = build_global_metacatalog(
    lst_merged,
    assoc_bands=ASSOC_BANDS,
    band_fields=BAND_FIELDS,
    color_bands=COLOR_BANDS,
)
meta_path = write_metacatalog(metacatalog, layout)

n_inputs = sum(len(df) for df in lst_merged.values())
print(f"\nGlobal metacatalog: {len(metacatalog)} sources from {n_inputs} LST-merged-shaped rows")
print(f"Wrote {meta_path}")
print(
    f"Per-band flux columns ({len(per_band_flux_columns())}): "
    f"{', '.join(per_band_flux_columns()[:4])}, ..."
)
metacatalog.head(10)

ValueError: could not convert string to float: 'healpix'

In [ ]:
# Tile→LST yield (Full band)
full_lst = lst_merged["Full"]
print(f"Full-band sources after tile merge: {len(full_lst)}")
if len(full_lst) and "n_lst_contributions" in full_lst.columns:
    multi = full_lst[full_lst["n_lst_contributions"] > 1]
    print(f"  n_lst_contributions > 1 (unexpected for single coadd): {len(multi)}")

# Global band merge
print(f"\nGlobal rows by origin_band:")
print(metacatalog["origin_band"].value_counts())

full_with_color = metacatalog[
    (metacatalog["origin_band"] == "Full")
    & (metacatalog[[f"n_assoc_{b}" for b in ASSOC_BANDS]].max(axis=1) > 0)
]
print(f"Full-seeded rows with at least one color-band association: {len(full_with_color)}")

summary_cols = [
    "meta_id",
    "RA",
    "DEC",
    "origin_band",
    "bands_present",
    "Peak_flux",
    "Total_flux",
    "E_Peak_flux",
    "E_Total_flux",
    "Peak_flux_std",
    *[f"n_assoc_{b}" for b in ASSOC_BANDS],
]
summary_cols = [c for c in summary_cols if c in metacatalog.columns]
display(metacatalog.head(10)[summary_cols])

flux_cols = ["meta_id", "origin_band", "bands_present", *per_band_flux_columns()]
flux_cols = [c for c in flux_cols if c in metacatalog.columns]
print(f"\nPer-band flux columns ({len(flux_cols) - 3} flux fields × {len(COLOR_BANDS)} bands):")
display(metacatalog.head(10)[flux_cols])

## Fit quality

Summarize detection fit quality on **`lst_merged`** (tile-merged representative-row residuals and fluxes).
Requires the fusion cells above so `lst_merged` is populated.

Three categories:

1. **Island residual stats** — flag the top 1% of `Resid_Isl_rms` and the top 1% of
   `|Resid_Isl_mean|` within each band (union = high-residual set).
2. **Unphysical flux ratio** — allow `Total_flux < Peak_flux` within error; flag only when
   `(Total_flux - Peak_flux) / hypot(E_Total_flux, E_Peak_flux) < -3`.
   Rows missing either error are not flagged.
3. **Source density** — 1°×1° RA–Dec histogram; report densest bins and overlay flagged
   sources on a Full-band map. Flat RA–Dec bins exaggerate area near the NCP.

This section is read-only QA (does not rewrite Parquet catalogs).

In [ ]:
import numpy as np

FLUX_UNPHYSICAL_NSIGMA = 3.0
RESIDUAL_PERCENTILE = 99.0  # top 1%
DENSITY_BIN_DEG = 3.0
FIT_QA_DISPLAY_ROWS = 15

_RESID_COLS = ("Resid_Isl_rms", "Resid_Isl_mean")
_FLUX_COLS = ("Total_flux", "Peak_flux", "E_Total_flux", "E_Peak_flux")
_POS_COLS = ("RA", "DEC")


def _missing_columns(df: pd.DataFrame, cols: tuple[str, ...]) -> list[str]:
    return [c for c in cols if c not in df.columns]


def flux_sigma_total_minus_peak(df: pd.DataFrame) -> pd.Series:
    """Return (Total - Peak) / hypot(E_Total, E_Peak); non-finite where inputs invalid."""
    missing = _missing_columns(df, _FLUX_COLS)
    if missing:
        return pd.Series(np.nan, index=df.index, dtype=float)
    total = df["Total_flux"].to_numpy(dtype=float)
    peak = df["Peak_flux"].to_numpy(dtype=float)
    e_tot = df["E_Total_flux"].to_numpy(dtype=float)
    e_peak = df["E_Peak_flux"].to_numpy(dtype=float)
    denom = np.hypot(e_tot, e_peak)
    sigma = np.full(len(df), np.nan, dtype=float)
    ok = (
        np.isfinite(total)
        & np.isfinite(peak)
        & np.isfinite(e_tot)
        & np.isfinite(e_peak)
        & (denom > 0)
    )
    sigma[ok] = (total[ok] - peak[ok]) / denom[ok]
    return pd.Series(sigma, index=df.index, name="flux_sigma_T_minus_P")


def flag_unphysical_flux(
    df: pd.DataFrame, *, nsigma: float = FLUX_UNPHYSICAL_NSIGMA
) -> pd.Series:
    """True where Total is significantly below Peak (sigma < -nsigma). Missing errors → False."""
    sigma = flux_sigma_total_minus_peak(df)
    return (sigma < -float(nsigma)).fillna(False).rename("unphysical_flux")


def flag_residual_top_percentile(
    df: pd.DataFrame, *, percentile: float = RESIDUAL_PERCENTILE
) -> pd.DataFrame:
    """Boolean columns: high_resid_rms, high_resid_abs_mean, high_residual (union)."""
    out = pd.DataFrame(index=df.index)
    missing = _missing_columns(df, _RESID_COLS)
    if missing:
        out["high_resid_rms"] = False
        out["high_resid_abs_mean"] = False
        out["high_residual"] = False
        return out

    rms = df["Resid_Isl_rms"].to_numpy(dtype=float)
    mean = df["Resid_Isl_mean"].to_numpy(dtype=float)
    abs_mean = np.abs(mean)

    high_rms = np.zeros(len(df), dtype=bool)
    high_abs = np.zeros(len(df), dtype=bool)

    finite_rms = np.isfinite(rms)
    if finite_rms.any():
        thr_rms = np.nanpercentile(rms[finite_rms], percentile)
        high_rms = finite_rms & (rms >= thr_rms)

    finite_abs = np.isfinite(abs_mean)
    if finite_abs.any():
        thr_abs = np.nanpercentile(abs_mean[finite_abs], percentile)
        high_abs = finite_abs & (abs_mean >= thr_abs)

    out["high_resid_rms"] = high_rms
    out["high_resid_abs_mean"] = high_abs
    out["high_residual"] = high_rms | high_abs
    return out


def sky_density_histogram(
    df: pd.DataFrame, *, bin_deg: float = DENSITY_BIN_DEG
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (H, ra_edges, dec_edges) for finite RA/DEC with fixed bin width in degrees."""
    missing = _missing_columns(df, _POS_COLS)
    if missing:
        return np.zeros((0, 0)), np.array([]), np.array([])
    ra = df["RA"].to_numpy(dtype=float)
    dec = df["DEC"].to_numpy(dtype=float)
    ok = np.isfinite(ra) & np.isfinite(dec)
    if not ok.any():
        return np.zeros((0, 0)), np.array([]), np.array([])
    ra = ra[ok]
    dec = dec[ok]
    bin_deg = float(bin_deg)
    ra_min, ra_max = np.floor(ra.min() / bin_deg) * bin_deg, np.ceil(ra.max() / bin_deg) * bin_deg
    dec_min, dec_max = np.floor(dec.min() / bin_deg) * bin_deg, np.ceil(dec.max() / bin_deg) * bin_deg
    if ra_max <= ra_min:
        ra_max = ra_min + bin_deg
    if dec_max <= dec_min:
        dec_max = dec_min + bin_deg
    n_ra = max(1, int(np.round((ra_max - ra_min) / bin_deg)))
    n_dec = max(1, int(np.round((dec_max - dec_min) / bin_deg)))
    ra_edges = ra_min + np.arange(n_ra + 1) * bin_deg
    dec_edges = dec_min + np.arange(n_dec + 1) * bin_deg
    H, _, _ = np.histogram2d(ra, dec, bins=[ra_edges, dec_edges])
    return H, ra_edges, dec_edges


def densest_bins(
    H: np.ndarray,
    ra_edges: np.ndarray,
    dec_edges: np.ndarray,
    *,
    n: int = 10,
) -> pd.DataFrame:
    """Return the densest histogram bins (count, bin centers)."""
    if H.size == 0:
        return pd.DataFrame(columns=["count", "RA_center", "DEC_center", "i_ra", "i_dec"])
    flat = H.ravel()
    order = np.argsort(flat)[::-1]
    rows = []
    for idx in order[: max(0, int(n))]:
        if flat[idx] <= 0:
            break
        i_ra, i_dec = np.unravel_index(int(idx), H.shape)
        rows.append(
            {
                "count": int(flat[idx]),
                "RA_center": float(0.5 * (ra_edges[i_ra] + ra_edges[i_ra + 1])),
                "DEC_center": float(0.5 * (dec_edges[i_dec] + dec_edges[i_dec + 1])),
                "i_ra": int(i_ra),
                "i_dec": int(i_dec),
            }
        )
    return pd.DataFrame(rows)


print(
    f"Fit-quality helpers ready "
    f"(residual p{RESIDUAL_PERCENTILE:g}, unphysical {FLUX_UNPHYSICAL_NSIGMA:g}σ, "
    f"density {DENSITY_BIN_DEG:g}°)."
)

In [ ]:
# Per-band residual + unphysical flux summaries (stores fit_qa for density overlay)
fit_qa: dict[str, dict] = {}

for band in COLOR_BANDS:
    df = lst_merged[band]
    print(f"\n=== {band}: {len(df)} LST-merged sources ===")
    entry: dict = {
        "n_sources": int(len(df)),
        "high_residual": pd.Series(False, index=df.index),
        "unphysical_flux": pd.Series(False, index=df.index),
        "flux_sigma": pd.Series(np.nan, index=df.index),
        "skipped_residual": False,
        "skipped_flux": False,
    }

    miss_resid = _missing_columns(df, _RESID_COLS)
    if miss_resid:
        print(f"  SKIP residual QA — missing columns: {miss_resid}")
        entry["skipped_residual"] = True
        entry["n_resid_top1"] = 0
    else:
        flags = flag_residual_top_percentile(df, percentile=RESIDUAL_PERCENTILE)
        entry["high_residual"] = flags["high_residual"]
        entry["n_resid_top1"] = int(flags["high_residual"].sum())
        n_rms = int(flags["high_resid_rms"].sum())
        n_abs = int(flags["high_resid_abs_mean"].sum())
        n_finite_rms = int(np.isfinite(df["Resid_Isl_rms"].to_numpy(dtype=float)).sum())
        print(
            f"  Residual top-1%: union={entry['n_resid_top1']} "
            f"(rms={n_rms}, |mean|={n_abs}; finite Resid_Isl_rms={n_finite_rms})"
        )
        show_cols = [c for c in ["RA", "DEC", "Peak_flux", "Resid_Isl_rms", "Resid_Isl_mean", "S_Code"] if c in df.columns]
        outliers = (
            df.loc[flags["high_residual"], show_cols]
            .assign(_sort=df.loc[flags["high_residual"], "Resid_Isl_rms"])
            .sort_values("_sort", ascending=False)
            .drop(columns="_sort")
            .head(FIT_QA_DISPLAY_ROWS)
        )
        if len(outliers):
            display(outliers)
        else:
            print("  (no residual outliers)")

    miss_flux = _missing_columns(df, _FLUX_COLS)
    if miss_flux:
        print(f"  SKIP unphysical-flux QA — missing columns: {miss_flux}")
        entry["skipped_flux"] = True
        entry["n_unphysical_3sig"] = 0
    else:
        sigma = flux_sigma_total_minus_peak(df)
        unphys = flag_unphysical_flux(df, nsigma=FLUX_UNPHYSICAL_NSIGMA)
        entry["flux_sigma"] = sigma
        entry["unphysical_flux"] = unphys
        entry["n_unphysical_3sig"] = int(unphys.sum())
        print(f"  Unphysical flux (σ < -{FLUX_UNPHYSICAL_NSIGMA:g}): {entry['n_unphysical_3sig']}")
        show_cols = [c for c in ["RA", "DEC", "Total_flux", "Peak_flux", "E_Total_flux", "E_Peak_flux"] if c in df.columns]
        bad = df.loc[unphys, show_cols].copy()
        bad.insert(0, "flux_sigma_T_minus_P", sigma.loc[unphys])
        bad = bad.sort_values("flux_sigma_T_minus_P").head(FIT_QA_DISPLAY_ROWS)
        if len(bad):
            display(bad)
        else:
            print("  (no unphysical-flux sources)")

    fit_qa[band] = entry

print("\nStored per-band flags in fit_qa.")

In [ ]:
import matplotlib.pyplot as plt

# Full-band 1° density map + flagged overlays; roll-up for all bands
primary_band = "Full" if "Full" in lst_merged else COLOR_BANDS[0]
df_full = lst_merged[primary_band]
H, ra_edges, dec_edges = sky_density_histogram(df_full, bin_deg=DENSITY_BIN_DEG)
top_bins = densest_bins(H, ra_edges, dec_edges, n=10)
print(f"Densest {DENSITY_BIN_DEG:g}° bins ({primary_band}):")
display(top_bins)

if H.size:
    fig, ax = plt.subplots(figsize=(8, 6))
    # H is (n_ra, n_dec); pcolormesh expects X,Y as edges
    mesh = ax.pcolormesh(ra_edges, dec_edges, H.T, shading="auto", cmap="viridis")
    fig.colorbar(mesh, ax=ax, label="sources / bin")
    qa = fit_qa.get(primary_band, {})
    high = qa.get("high_residual", pd.Series(False, index=df_full.index))
    unphys = qa.get("unphysical_flux", pd.Series(False, index=df_full.index))
    if high.any():
        ax.scatter(
            df_full.loc[high, "RA"],
            df_full.loc[high, "DEC"],
            s=12,
            c="orange",
            marker="o",
            label=f"residual top-1% ({int(high.sum())})",
            zorder=3,
        )
    if unphys.any():
        ax.scatter(
            df_full.loc[unphys, "RA"],
            df_full.loc[unphys, "DEC"],
            s=18,
            c="red",
            marker="x",
            label=f"unphysical 3σ ({int(unphys.sum())})",
            zorder=4,
        )
    ax.set_xlabel("RA (deg)")
    ax.set_ylabel("DEC (deg)")
    ax.set_title(f"{primary_band} source density ({DENSITY_BIN_DEG:g}° bins)")
    ax.set_aspect("equal", adjustable="box")
    ax.legend(loc="best", fontsize=8)
    fig.tight_layout()
    plt.show()
else:
    print(f"No finite RA/DEC for density map ({primary_band}).")

# Roll-up summary across bands
rows = []
for band in COLOR_BANDS:
    df = lst_merged[band]
    qa = fit_qa.get(band, {})
    H_b, _, _ = sky_density_histogram(df, bin_deg=DENSITY_BIN_DEG)
    max_bin = int(H_b.max()) if H_b.size else 0
    high = qa.get("high_residual", pd.Series(False, index=df.index))
    unphys = qa.get("unphysical_flux", pd.Series(False, index=df.index))
    rows.append(
        {
            "band": band,
            "n_sources": int(len(df)),
            "n_resid_top1": int(qa.get("n_resid_top1", high.sum())),
            "n_unphysical_3sig": int(qa.get("n_unphysical_3sig", unphys.sum())),
            "max_bin_count": max_bin,
            "n_resid_and_unphysical": int((high & unphys).sum()),
        }
    )

fit_qa_summary = pd.DataFrame(rows)
print("\nFit-quality roll-up:")
display(fit_qa_summary)